"""add user model to db

Revision ID: a391168eb754
Revises: 5c720510a448
Create Date: 2026-03-16 11:08:32.997020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a391168eb754'
down_revision = '5c720510a448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=1000000), nullable=False))
        batch_op.drop_column('pasword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasword', sa.VARCHAR(length=1000000), nullable=False))
        batch_op.drop_column('password')

    op.drop_table('user')
    # ### end Alembic commands ###
